apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: curl-probe-${SUFFIX}
  name: curl-probe-${SUFFIX}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: curl-probe-${SUFFIX}
  strategy:
    rollingUpdate:
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: curl-probe-${SUFFIX}
    spec:
      initContainers:
      - image: quay.io/pbertera/net-tools:latest
        restartPolicy: Always
        name: probe-puller
        command:
        - /bin/sh
        - -c
        - "curl -sk -o /work-dir/probe.sh https://raw.githubusercontent.com/pbertera/prober/refs/heads/main/probe-amadeus.sh; chmod +x /work-dir/probe.sh; sleep inf"
        volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
      containers:
      - name: probe-prober
        env:
        - name: HOST
          value: www.google.com
        - name: SLEEP
          value: "1"
        - name: PORT
          value: "80"
        - name: LOGDIR
          value: /log-dir
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: quay.io/pbertera/net-tools:latest
        command:
        - /bin/bash
        - /work-dir/probe.sh
        imagePullPolicy: Always
        volumeMounts:
        - name: logdir
          mountPath: "/log-dir"
        - name: workdir
          mountPath: "/work-dir"
      restartPolicy: Always
      volumes:
      - name: workdir
        emptyDir: {}
      - name: logdir
        persistentVolumeClaim:
          claimName: probe
